services:
  fines:
    build: .
    container_name: fines
    volumes:
      - .:/app
    working_dir: /app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fines.rule=Host(`fines.wrlc.localhost`)"
      - "traefik.http.routers.fines.tls=true"
      - "traefik.http.routers.fines.entrypoints=websecure"
    networks:
      - proxy

networks:
  proxy:
    external: true
